- name: Conditions
  host: local
  connection: local
  vars:
    number: 5
  tasks:
  - name: check the number is less than 10
    ansible.builtin.debug:
         msg: "Given number {{number}} less than 10"
    when: number < 10